Acme\Comment:
  type: entity
  id:
    id:
      type: integer
      length: 10
      generator:
        strategy: AUTO
  fields:
    message:
      type: string
  manyToOne:
    article:
      targetEntity: Article
